version: "3.9"
services:
  web:
    container_name: law-web-app
    build: .
    ports:
      - "8080:8080"
    networks:
      - network

networks:
  network:
    driver: bridge
    name: law-network 